### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by fznx922** [Pikurrot/whisper-gui#18]
Hey mate, after installing the newest version fresh im getting this error 

  File "C:\Users\fznx\anaconda3\envs\whisperxgui\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

i havent had any issues running any other cuda related things on my computer, ive double checked and tried to fresh install a few times without any help 

any advise or know how to fix it? 

thanks :)

**Comment by Pikurrot** [comment]
Hey, it seems a problem with PyTorch installation to work with CUDA. I assume you have a Windows and GPU in your computer. If you have already [installed a CUDA version ≥12](https://developer.nvidia.com/cuda-downloads), then try uninstalling PyTorch from your environment and installing it again correctly:
```
conda activate whisperxgui
conda uninstall pytorch torchaudio pytorch-cuda
conda install pytorch torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```
Let me know if you have further problems.

**Comment by fznx922** [comment]
hey mate, thanks for the reply, after doing that i got this now 

ModuleNotFoundError: No module named 'idna'

ive tried manually installing it in the enviroment, it says its installed but doesnt seem to find it regardless

**Comment by Pikurrot** [comment]
This is strange. Make sure in your `config.json` file inside `configs/` you have a variable `"env_name"` with the exact same name as your conda environment, which should be `whisperxgui`. This is what the script uses to run the program, but you can try to run it yourself manually:
```
conda activate whisperxgui
python main.py --autolaunch
```
This is assuming you've installed "idna" correctly with `pip install idna`. However, it's strange because this should have been installed automatically.

**Comment by fznx922** [comment]
so i tried a complete fresh environment, now could get back in, but still having the torch compile error again, this is with cuda toolkit installed really scratching my head, cant figure out whats doing it  

did notice this at the start Model was trained with torch 1.10.0+cu102, yours is 2.2.0+cpu. 

but definitionally chose GPU it detected it fine in the pre installation trying to uninstall and reinstall caused the idna issue again so i guess when it uninstalled it took something with it that it didnt get back reinstalling torch

**Comment by Pikurrot** [comment]
Don't worry about the `Model was trained ...` warning, that [often appears in WhisperX](https://github.com/m-bain/whisperX/issues/258) and is not a problem.
Regarding your error, CUDA errors are popular and often really diverse across different computers or OS. I couldn't replicate your problem so I'm not sure how to help you. :disappointed: 
Again, this is a CUDA error, shouldn't have nothing to do at all with my program, so you could try to rerun the `whisper-gui.bat` script, creating a new environment but this time selecting to not use the GPU. Note that you would have to delete the `config.json` file before, for a fresh start.
So with CPU should work properly.
