### ISSUE TITLE
AMD GPU?

### ISSUE THREAD

**Issue by rainforest-9716** [Pikurrot/whisper-gui#19]
Is there any method that we can use AMD rocm instead of NVIDIA cuda?

**Comment by Pikurrot** [comment]
Hi, I'm not very familiar with AMD GPUs. You can try to manually [install Pytorch](https://pytorch.org/get-started/locally/) in your conda environment, selecting the ROCm option. I'm not sure if that would be enough, maybe some changes in the program or the installer would be necessary, so I invite you or anyone that is more familiar with AMD GPUs to contribute to this project.  
Make me know if you are able to do it, I will take note of this as future work.

**Comment by Pikurrot** [comment]
With the last release [v2.3.0](https://github.com/Pikurrot/whisper-gui/releases/tag/v2.3.0) the installer and the program should now  support AMD ROCm too.
Feel free to reopen this issue or a new one if there is any problem.
