### ISSUE TITLE
saving error unicode charmap

### ISSUE THREAD

**Issue by fznx922** [Pikurrot/whisper-gui#2]
Hey mate trying to transcribe japanese, when it gets to the end and goes to save it errors with this message 

  File "C:\Users\fznx\whisper-gui\main.py", line 113, in transcribe_audio
    save_transcription_to_txt(joined_text, save_dir)
  File "C:\Users\fznx\whisper-gui\main.py", line 46, in save_transcription_to_txt
    f.write(text_str)
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-56: character maps to <undefined>

i assume because its using japanese and the default is looking for english characaters? but im not sure on how to fix it 

thanks :)

**Comment by Pikurrot** [comment]
Hi, as you said, I guess it's because it's trying to save Japanese characters into a plain text file (.txt). I will look into it, thanks pointing it out.

**Comment by fznx922** [comment]
had any luck with it?

**Comment by Pikurrot** [comment]
Hi, sorry, I have been busy. I will take a look as soon as I can, I didn't forget it :)

**Comment by Pikurrot** [comment]
It seems to work now. `git pull` the last changes and check if it works fine now!
