### ISSUE TITLE
Browser page not displaying

### ISSUE THREAD

**Issue by crazyfoxkp** [Pikurrot/whisper-gui#24]
Hi, 
successful installation on Linux popos 22 with NVIDIA gpu.
I see this message and no changes on the browser tabs. 

`Dependencies installed.
Checking for updates...
Your repository is up to date.
Checking auto update setting...
Do you want this repository to update automatically from now on? ([y]/n): y
This repository will update automatically from now on.
Saving result to config file...
Running Whisper-GUI...
`

any ideas?

**Comment by Pikurrot** [comment]
Hi,
it's a strange behavior. Doesn't it appear some message like `Running on local URL:  http://126.0.0.2:7860`? In that case you would need to enter that URL in the browser manually (although it should be done automatically).
If you don't see that URL nor any error message, then I don't know what's happening.
You can always try the rule of thumb: remove the repo and the conda environment, then try again installing the program and see if it works.

**Comment by crazyfoxkp** [comment]
All good now. Not sure why there was a hiccup. 
Thanks for your efforts.
